### ISSUE TITLE
There is a bug while tapping social media icons in the Readme.md

### ISSUE THREAD

**Issue by ayushsoni1010** [soumita1234/soumita1234#1]
In your GitHub portfolio, there is a bug while we tap on social media and CodeChef too.
Can I fix it out :)
Links are not working properly.

![image](https://user-images.githubusercontent.com/76895975/122021561-64f54d00-cde3-11eb-93e3-fc9bbc139f4e.png)

**Comment by soumita1234** [comment]
> In your GitHub portfolio, there is a bug while we tap on social media and CodeChef too.
> Can I fix it out :)
> Links are not working properly.
> 
> ![image](https://user-images.githubusercontent.com/76895975/122021561-64f54d00-cde3-11eb-93e3-fc9bbc139f4e.png)

I know its not working. I am about to change the readme portion. I will do it 
Thanks for looking over!! :)

**Comment by soumita1234** [comment]
@ayushsoni1010  I think issue is fixed. can you check and conform ?

**Comment by ayushsoni1010** [comment]
> @ayushsoni1010 I think issue is fixed. can you check and conform ?

yeah, now it's working well
